### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by chpio** [getkirby/api-js#1]
Hi,

please add support for nodejs

* https://www.npmjs.com/package/cross-fetch

**Comment by distantnative** [comment]
I would love to keep this dependency-free if possible.
Wouldn't something like this work?

```javascript
import fetch from "cross-fetch";
import Api from "@getkirby/api-js";
```

**Comment by chpio** [comment]
Is there a GraphQL API (as a plugin or something) for Kirby, that would fix all the problems instantly by using a standard API.

> Wouldn't something like this work?

No, but maybe something like this:

```js
import fetch from "cross-fetch";
import Api from "@getkirby/api-js";

Api.config.fetch = fetch;
```
